In [1]:
import numpy as np
import pandas as pd #only used for read data
import matplotlib.pyplot as plt #only used for plots

In [46]:
# Softmax
class softmaxClassifier:
    # main functions
    def __init__(self,num_outputs,batchSize = 32,
                 Learning_Rate = 0.0001,n_Iteration = 200):
        self.Learning_Rate = Learning_Rate
        self.n_Iteration = n_Iteration
        self.num_outputs = num_outputs
        self.batchSize = batchSize
        
    def init_parameters(self, X):
        self.num_features, self.num_observation = X.shape[1], X.shape[0]
        self.W1 = np.random.randn(self.num_features,self.num_outputs)*0.01
        self.b1 = np.random.randn(1,self.num_outputs)
    
    def net(self,X):
        Z1 = X@self.W1+self.b1
        self.A1 = self.Softmax(Z1)
    
    def backPropagation(self,X,y):
        dZ = self.A1 - self.one_hot(y)
        dW = np.dot(X.T,dZ)/self.num_observation
        db = dZ.mean(0)
        # update parameters
        self.W1 = self.W1 - self.Learning_Rate*dW
        self.b1 = self.b1 - self.Learning_Rate*db
        
    def train(self, X, y):
        self.init_parameters(X)
        one_hot_Y = self.one_hot(y)
        self.accuracy = []
        self.crossEntropyLoss = []
        for i in range(self.n_Iteration):
            for X_b, y_b in self.data_iteration(X,y):
                self.net(X_b)
                self.backPropagation(X_b,y_b)
            if (i%20==0):
                self.net(X)
                (self.accuracy).append(self.get_accuracy(self.get_pred(self.A1),y))
                (self.crossEntropyLoss).append(self.crossEntropyLoss_2(self.one_hot_Y,self.A1))
                print("n_Iteration:",i)
                print("Accuracy:",self.accuracy[-1])
                print("crossEntropy", self.crossEntropyLoss[-1])
                #animator(i//20,self.accuracy,self.crossEntropyLoss)
        plt.show()
        
    def data_iteration(self, X, y):
        n = len(y)
        index = list(range(n))
        np.random.shuffle(index)
        for i in range(0, n, self.batchSize):
            batch_index = index[i:min(n, i+self.batchSize)]
            yield X[batch_index], y[batch_index]
    
    def test(self, X, y):
        self.net(X)
        one_hot_Y = self.one_hot(y)
        print("Accuracy:",self.get_accuracy(self.get_pred(self.A1),y))
        print("crossEntropy", self.crossEntropyLoss_2(one_hot_Y,self.A1))
    
    def predict(self, X):
        self.net(X)
        self.pred = self.get_pred(self.A1)
    
    # auxiliary code
    def Softmax(self,X):
        X_exp = np.exp(X)
        return (X_exp/(np.sum(X_exp,1,keepdims=True)))
    
    def one_hot(self,y):
        one_hot_Y = np.zeros((y.size, self.num_outputs))
        one_hot_Y[np.arange(y.size),y] = 1
        return one_hot_Y
    
    def crossEntropyLoss_2(self,one_hot_Y,y_hat):
        return (-(one_hot_Y*np.log(y_hat))).sum(1).mean()
    
    def get_pred(self,A1):
        return(np.argmax(A1,1))
    
    def get_accuracy(self,pred,y):
        print(pred,y)
        return np.sum(pred == y)/y.size

In [27]:
len(X)
def data_iteration(batchSize, X, y):
    n = len(y)
    index = list(range(n))
    np.random.shuffle(index)
    for i in range(0, n, batchSize):
        batch_index = index[i:min(n, i+batchSize)]
        yield X[batch_index], y[batch_index]

In [3]:
def animator(index, metrics1,metrics2):
    fig, ax = plt.subplots()
    
    iterations=[j for j in range(1, index+2)]
    ax.clear()

    ax.plot(iterations, metrics1, label='Accuracy')
    ax.plot(iterations, metrics2, label='CrossEntropy')
    ax.set_xlabel("Iterations")
    ax.set_ylabel("Metrics")
    ax.legend()  

    # update
    plt.pause(0.1)  
    plt.draw()

    

In [4]:
data = pd.read_csv("data/train.csv")
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [6]:
data = np.array(data)
np.random.shuffle(data)
X, y = data[:,1:],data[:,0]
n, m = X.shape

In [7]:
X_Train, X_Test = X[0:int(np.ceil(0.7*len(y))),:],X[int(np.ceil(0.7*len(y))):,:]
y_Train, y_Test = y[0:int(np.ceil(0.7*len(y)))],y[int(np.ceil(0.7*len(y))):]

In [47]:
SoM = softmaxClassifier(num_outputs=10)

In [48]:
SoM.train(X_Train,y_Train)

[9 7 5 ... 0 5 9] [7 0 4 ... 6 6 5]
n_Iteration: 0
Accuracy: 0.08877551020408163
crossEntropy 25.40903157557804
[9 0 4 ... 6 5 5] [7 0 4 ... 6 6 5]
n_Iteration: 20
Accuracy: 0.7259523809523809
crossEntropy 3.212301415406835
[9 0 4 ... 6 5 5] [7 0 4 ... 6 6 5]
n_Iteration: 40
Accuracy: 0.7920748299319728
crossEntropy 2.2392623388005473
[9 0 4 ... 6 0 5] [7 0 4 ... 6 6 5]
n_Iteration: 60
Accuracy: 0.8191496598639456
crossEntropy 1.8481433929447553
[9 0 4 ... 6 0 5] [7 0 4 ... 6 6 5]
n_Iteration: 80
Accuracy: 0.8349659863945578
crossEntropy 1.6232611266932901
[7 0 4 ... 6 0 5] [7 0 4 ... 6 6 5]
n_Iteration: 100
Accuracy: 0.8458163265306122
crossEntropy 1.4702766025373373
[7 0 4 ... 6 0 5] [7 0 4 ... 6 6 5]
n_Iteration: 120
Accuracy: 0.8527551020408163
crossEntropy 1.3560138854459256
[7 0 4 ... 6 0 5] [7 0 4 ... 6 6 5]
n_Iteration: 140
Accuracy: 0.8586054421768707
crossEntropy 1.2656464018206761
[7 0 4 ... 6 0 5] [7 0 4 ... 6 6 5]
n_Iteration: 160
Accuracy: 0.8626190476190476
crossEntropy 

In [49]:
SoM.test(X_Test,y_Test)

[0 5 2 ... 6 8 4] [0 5 2 ... 6 8 4]
Accuracy: 0.8612698412698413
crossEntropy 1.21351177942318


In [10]:
np.ceil(0.7*len(y))

29400.0

In [11]:
#scratch
def Relu(X):
    a = np.zeros_like(X)
    return np.maximum(X,a)

def Tahn(X):
    return np.tanh(X)

def Sigmoid(X):
    return 1/(1+np.exp(-X))

def Softmax(X):
    X_exp = np.exp(X)
    return (X_exp/(np.sum(X_exp,1,keepdims=True)))
    

In [12]:
np.max(X,1).shape
Softmax(X).max(1)

array([0.07078011, 0.05143383, 0.1987892 , ..., 0.04580855, 0.05020387,
       0.04254311])

In [13]:
# Initailize the parameters
def init_parameters(X):
    num_features, num_outputs = X.shape[1], 10
    W1 = np.random.randn(num_features,num_outputs)*0.01
    b1 = np.random.randn(1,num_outputs)
    return W1,b1

In [14]:
def net(W1, b1,X):
    Z1 = X@W1+b1
    A1 = Softmax(Z1)
    return(Z1, A1)

In [50]:
def one_hot(y):
    one_hot_Y = np.zeros((y.size, y.max()+1))
    one_hot_Y[np.arange(y.size),y] = 1
    return one_hot_Y

In [51]:
def data_iteration(batchSize, X, y):
    n = len(y)
    index = list(range(n))
    np.random.shuffle(index)
    for i in range(0, n, batchSize):
        batch_index = index[i:min(n, i+batchSize)]
        yield X[batch_index], y[batch_index]

In [16]:
def crossEntropyLoss_2(one_hot_Y,y_hat):
    return (-(one_hot_Y*np.log(y_hat))).sum(1).mean()

def crossEntropyLoss(y,y_hat):
    return(-np.mean(np.log(y_hat[list(range(len(y_hat))), y])))

In [18]:
def backPropagation(A1, W1, b1, lr, X,y):
    n = len(y)
    dZ = A1 - one_hot(y)
    dW = np.dot(X.T,dZ)/n
    db = dZ.mean(0)
    # update parameters
    W1 = W1 - lr*dW
    b1 = b1 - lr*db
    return W1, b1

In [20]:
def get_pred(A1):
    return(np.argmax(A1,1))
def get_accuracy(pred,y):
    print(pred,y)
    return np.sum(pred == y)/y.size

In [21]:
def gradient_decent(X, Y, n_iterations, lr):
    W1, b1 = init_parameters(X)
    one_hot_Y = one_hot(Y)
    for i in range(n_iterations):
        Z1, A1 = net(W1, b1, X)
        W1, b1 = backPropagation(A1, W1, b1,lr,X,Y)
        if (i%20==0):
            print("n_Iteration:",i)
            print("Accuracy:",get_accuracy(get_pred(A1),Y))
            print("crossEntropy", crossEntropyLoss_2(one_hot_Y,A1))
    return W1, b1

In [22]:
W1,b1 = gradient_decent(X_Train,y_Train, 200, 0.0001)

n_Iteration: 0
[2 2 2 ... 4 2 4] [4 0 1 ... 5 8 0]
Accuracy: 0.1226530612244898
crossEntropy 45.038692051837806
n_Iteration: 20
[9 0 1 ... 3 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.7217346938775511
crossEntropy 3.758094280437829
n_Iteration: 40
[9 0 1 ... 5 3 6] [4 0 1 ... 5 8 0]
Accuracy: 0.8001020408163265
crossEntropy 2.3441127981490157
n_Iteration: 60
[9 0 1 ... 5 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.8207142857142857
crossEntropy 1.9955709894183713
n_Iteration: 80
[9 0 1 ... 5 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.8320408163265306
crossEntropy 1.7823801812542208
n_Iteration: 100
[9 0 1 ... 5 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.8407482993197279
crossEntropy 1.61888313409676
n_Iteration: 120
[9 0 1 ... 5 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.8399319727891157
crossEntropy 1.5866631249529435
n_Iteration: 140
[9 0 1 ... 5 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.8527551020408163
crossEntropy 1.4298658739107826
n_Iteration: 160
[9 0 1 ... 5 3 8] [4 0 1 ... 5 8 0]
Accuracy: 0.8576530612244898
crossEntropy 1.

In [26]:
_,pred_A1 = net(W1,b1,X_Test)
get_accuracy(get_pred(pred_A1),y_Test)

[1 7 9 ... 0 5 5] [1 9 9 ... 0 5 5]


0.8592857142857143