In [1]:
import numpy as np

In [12]:
def data_iteration(batchSize, X, y):
    n = len(y)
    index = list(range(n))
    np.random.shuffle(index)
    for i in range(0, n, batchSize):
        batch_index = index[i:min(n, i+batchSize)]
        yield X[batch_index], y[batch_index]

In [19]:
X = np.array([[1,2,3],
             [2,3,4],
             [3,4,5],
             [4,5,6],
             [5,6,7]])
y = np.array([2,3,4,5,6])

for a,b in data_iteration(2,X,y):
    print('batch i')
    print(a,'\n',b)
    print('--------------')

batch i
[[1 2 3]
 [3 4 5]] 
 [2 4]
--------------
batch i
[[4 5 6]
 [5 6 7]] 
 [5 6]
--------------
batch i
[[2 3 4]] 
 [3]
--------------
