In [1]:
import numpy as np

In [17]:
def cv_k_fold(k,i,X,y):
    assert k>1
    foldSize = X.shape[0]//k
    X_Train, y_Train = None, None
    for m in range(k):
        idx = slice(m * foldSize, (m+1)*foldSize)
        X_p, y_p = X[idx,:],y[idx]
        if m == i:
            X_v, y_v = X_p, y_p
        elif X_Train is None:
            X_Train, y_Train = X_p, y_p
        else:
            X_Train = np.concatenate((X_Train,X_p), 0)
            y_Train = np.concatenate((y_Train,y_p), 0)
    return X_Train, y_Train, X_v, y_v

In [6]:
slice(3 * 10, 4*10)

slice(30, 40, None)

In [18]:
X = np.array([[1,2,3],
          [2,3,4],
          [3,4,5],
          [4,5,6],
          [6,7,8]])
y = np.array([1,2,3,4,5])
cv_k_fold(2,0,X,y)

(array([[3, 4, 5],
        [4, 5, 6]]),
 array([3, 4]),
 array([[1, 2, 3],
        [2, 3, 4]]),
 array([1, 2]))